# Generated by Django 5.1 on 2024-08-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_rename_phonenumber_user_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
