# Generated by Django 5.1 on 2024-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_campaign_alter_admin_table_alter_registration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
