# Generated by Django 5.1 on 2024-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_campaign_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('blood_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
