# Generated by Django 5.1 on 2024-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registrations',
        ),
    ]
