# Generated by Django 5.1 on 2024-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
