# Generated by Django 5.0 on 2024-10-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_inventory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype'),
        ),
    ]
