# Generated by Django 5.0 on 2024-10-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_alter_registration_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
