# Generated by Django 5.1 on 2024-10-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_alter_registration_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='id',
            new_name='user_id',
        ),
    ]
