# Generated by Django 5.1 on 2024-10-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_alter_registration_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_type', models.ForeignKey(db_column='blood_type_id', on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='blood.registration')),
            ],
        ),
    ]
