# Generated by Django 5.1 on 2024-10-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
