# Generated by Django 5.1 on 2024-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0014_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
