# Generated by Django 5.1 on 2024-10-09 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_campaign_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='blood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.registration'),
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
            ],
        ),
    ]
