# Generated by Django 5.1 on 2024-10-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_campaign_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_requested', models.IntegerField()),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('blood_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.recipient')),
            ],
        ),
    ]
