# Generated by Django 5.1 on 2024-10-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_alter_recipient_blood_type_alter_recipient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
