# Generated by Django 5.1 on 2024-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
