# Generated by Django 5.1 on 2024-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_alter_bloodrequest_units_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
