# Generated by Django 5.1 on 2024-10-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0020_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
