# Generated by Django 5.1 on 2024-10-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0023_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
