# Generated by Django 5.1 on 2024-10-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0025_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity in units (e.g., 1 unit = 500ml)')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('urgency', models.CharField(blank=True, choices=[('normal', 'Normal'), ('emergency', 'Emergency')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_applications', to='blood.hospital')),
            ],
        ),
    ]
