# Generated by Django 5.1 on 2024-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0026_bloodapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodapply',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
