# Generated by Django 5.1 on 2024-10-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0027_bloodapply_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodApply',
        ),
    ]
