# Generated by Django 5.1 on 2024-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0029_bloodapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
