# Generated by Django 5.1 on 2024-10-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0030_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
