# Generated by Django 5.1 on 2024-10-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0031_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
