# Generated by Django 5.1 on 2024-10-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0033_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'donor_profiles',
            },
        ),
    ]
