# Generated by Django 5.1 on 2024-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0035_donorprofile_blood_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
