# Generated by Django 5.1 on 2024-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0040_hospital_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='hospital_documents/'),
        ),
    ]
