# Generated by Django 5.1 on 2024-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0041_hospital_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
