# Generated by Django 5.1 on 2024-10-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0042_hospital_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='document',
        ),
    ]
