# Generated by Django 5.1 on 2024-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0045_alter_hospital_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
