# Generated by Django 5.1 on 2025-01-17 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0047_plasmadonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateletsDonation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('count', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donorprofile')),
            ],
        ),
    ]
