# Generated by Django 5.1 on 2025-01-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0048_plateletsdonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlateletsDonation',
        ),
    ]
