# Generated by Django 5.1 on 2025-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0049_delete_plateletsdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateletsDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)')], max_length=3, verbose_name='Blood Type')),
                ('donation_date', models.DateField(blank=True, null=True, verbose_name='Available Date')),
                ('donation_time', models.TimeField(blank=True, null=True, verbose_name='Available Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
            ],
        ),
    ]
