# Generated by Django 5.1 on 2025-01-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0050_plateletsdonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlasmaDonation',
        ),
    ]
