# Generated by Django 5.1 on 2025-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0052_plasmadonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.PositiveIntegerField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.PositiveIntegerField(help_text='Enter quantity in units')),
                ('hospital', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('reason', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
