# Generated by Django 5.1 on 2025-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0053_plasmarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='plasma_available',
            field=models.IntegerField(default=0),
        ),
    ]
