# Generated by Django 5.1 on 2025-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0054_inventory_plasma_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmarequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
