# Generated by Django 5.1 on 2025-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0056_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
