# Generated by Django 5.1 on 2025-01-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0057_donorprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
