# Generated by Django 5.1 on 2025-02-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0058_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donorprofile')),
            ],
        ),
    ]
