# Generated by Django 5.1 on 2025-02-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0059_blooddonationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_rate', models.IntegerField()),
                ('hemoglobin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_eligible', models.BooleanField(default=False)),
                ('screening_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.blooddonationrequest')),
            ],
        ),
    ]
