# Generated by Django 5.1 on 2025-02-06 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0060_basicscreening'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv', models.BooleanField(default=False)),
                ('hepatitis_b', models.BooleanField(default=False)),
                ('hepatitis_c', models.BooleanField(default=False)),
                ('syphilis', models.BooleanField(default=False)),
                ('malaria', models.BooleanField(default=False)),
                ('hemoglobin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('tested_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('is_safe', models.BooleanField(default=False)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.blooddonationrequest')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
