# Generated by Django 5.1 on 2025-02-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0061_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('medical_condition', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_doctor', models.BooleanField(default=False)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital')),
            ],
        ),
    ]
