# Generated by Django 5.1 on 2025-02-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0062_recipientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRecipientMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ml_confidence', models.FloatField()),
                ('donor_response', models.BooleanField(null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodapply')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donorprofile')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.DeleteModel(
            name='RecipientProfile',
        ),
    ]
