# Generated by Django 5.1 on 2025-02-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0063_donorrecipientmatch_delete_recipientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_demand', models.IntegerField()),
                ('prediction_date', models.DateField()),
                ('confidence_score', models.FloatField()),
                ('actual_demand', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
