# Generated by Django 5.1 on 2025-02-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0064_blooddemandprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital')),
            ],
            options={
                'ordering': ['-demand_date'],
            },
        ),
    ]
