# Generated by Django 5.1 on 2025-02-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0066_bloodtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorIronStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_ferritin', models.FloatField(help_text='Iron storage levels (ng/ml)')),
                ('total_iron_binding_capacity', models.FloatField(help_text='TIBC (µg/dL)')),
                ('transferrin_saturation_index', models.FloatField(help_text='TSI (%)')),
                ('hemoglobin_level', models.FloatField(help_text='Hemoglobin (g/dL)')),
                ('donation_count_last_year', models.IntegerField()),
                ('iron_deficiency_status', models.CharField(blank=True, max_length=50)),
                ('diet_plan', models.TextField(blank=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.donorprofile')),
            ],
        ),
    ]
