# Generated by Django 5.1 on 2025-02-26 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0067_donorironstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRecipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('medical_history', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.bloodtype')),
            ],
        ),
    ]
