# Generated by Django 5.1 on 2025-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0068_bloodrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IronPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
                ('hemoglobin', models.FloatField()),
                ('mch', models.FloatField()),
                ('mchc', models.FloatField()),
                ('mcv', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
    ]
